export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED';
export const REQUEST_LOGOUT_SUCCESS = 'REQUEST_LOGOUT_SUCCESS';


export const REQUEST_ERROR = 'REQUEST_ERROR';

export const LOAD_LINES_SUCCESS = 'LOAD_LINES_SUCCESS';
export const LOAD_POSITIONS_SUCCESS = 'LOAD_POSITIONS_SUCCESS';
export const PRE_SELECT_ACTION = 'PRE_SELECT_ACTION';   // first screen after login

export const REQUEST_ACTION_SUCCESS = 'REQUEST_ACTION_SUCCESS';
export const REQUEST_ACTION_FAILED = 'REQUEST_ACTION_FAILED';

export const AUTHORIZATION_REQUIRED = 'AUTHORIZATION_REQUIRED';
export const AUTHORIZATION_CANCELED = 'AUTHORIZATION_CANCELED';
export const AUTHORIZATION_FILLED = 'AUTHORIZATION_FILLED';
export const AUTHORIZATION_SUCCESS = 'AUTHORIZATION_SUCCESS';
export const AUTHORIZATION_FAILED = 'AUTHORIZATION_FAILED';

export const SET_LANGUAGE = 'SET_LANGUAGE';
