export const ACTION_NONE = 'ACTION_NONE';
export const ACTION_LOGIN = 'ACTION_LOGIN';
export const ACTION_LOGOUT = 'ACTION_LOGOUT';
export const ACTION_EVENT_LOG = 'ACTION_EVENT_LOG';
export const ACTION_REPORT_ERROR_ELECTRIC = 'ACTION_REPORT_ERROR_ELECTRIC';
export const ACTION_REPORT_ERROR_MECHANIC = 'ACTION_REPORT_ERROR_MECHANIC';

// OPERATOR
export const ACTION_START_WORK = 'ACTION_START_WORK';
export const ACTION_END_WORK = 'ACTION_END_WORK';
export const ACTION_START_WORK_TRAINING = 'ACTION_START_WORK_TRAINING';
export const ACTION_END_WORK_TRAINING = 'ACTION_END_WORK_TRAINING';
export const ACTION_START_WORK_CONDITION = 'ACTION_START_WORK_CONDITION';
export const ACTION_END_WORK_CONDITION = 'ACTION_END_WORK_CONDITION';
export const ACTION_START_WORK_TEMPORARY = 'ACTION_START_WORK_TEMPORARY';
export const ACTION_END_WORK_TEMPORARY = 'ACTION_END_WORK_TEMPORARY';

// FOREMAN
export const ACTION_APPROVED_ACCESS = 'ACTION_APPROVED_ACCESS';
export const ACTION_START_REWORK = 'ACTION_START_REWORK';
export const ACTION_END_REWORK = 'ACTION_END_REWORK';
export const ACTION_START_OPERATOR = 'ACTION_START_OPERATOR';
export const ACTION_END_OPERATOR = 'ACTION_END_OPERATOR';

// TECHNOLOG
export const ACTION_START_TEST_WORK = 'ACTION_START_TEST_WORK';
export const ACTION_END_TEST_WORK = 'ACTION_END_TEST_WORK';

// REPAIRMAN
export const ACTION_START_REPAIR = 'ACTION_START_REPAIR';
export const ACTION_END_REPAIR = 'ACTION_END_REPAIR';

// QUALITY
export const ACTION_START_MSI = 'ACTION_START_MSI';
export const ACTION_END_MSI = 'ACTION_END_MSI';
export const ACTION_START_MSI2 = 'ACTION_START_MSI2';
export const ACTION_END_MSI2 = 'ACTION_END_MSI2';

// ITECHNIK
export const ACTION_INSTALL_TERMINAL = 'ACTION_INSTALL_TERMINAL';
export const ACTION_RESET_TERMINAL = 'ACTION_RESET_TERMINAL';
