


export const OPTION_LOGIN = 'OPTION_LOGIN';
export const OPTION_LOGOUT = 'OPTION_LOGOUT';
export const OPTION_BACK = 'OPTION_BACK';
export const OPTION_HOME = 'OPTION_HOME';

// OPERATOR
export const OPTION_START_WORK = 'OPTION_START_WORK';
export const OPTION_END_WORK = 'OPTION_END_WORK';

export const OPTION_SELECT_LINE = 'OPTION_SELECT_LINE';
export const OPTION_SELECT_POSITION = 'OPTION_SELECT_POSITION';

export const OPTION_REPORT_ERROR_ELECTRIC = 'OPTION_REPORT_ERROR_ELECTRIC';
export const OPTION_REPORT_ERROR_MECHANIC = 'OPTION_REPORT_ERROR_MECHANIC';

// FOREMAN
export const OPTION_START_TEMPORARY = 'OPTION_START_TEMPORARY';
export const OPTION_END_WORK_ON_POSITION = 'OPTION_END_WORK_ON_POSITION';
export const OPTION_END_WORK_ON_LINE = 'OPTION_END_WORK_ON_LINE';
export const OPTION_START_REWORK = 'OPTION_START_REWORK';
export const OPTION_END_REWORK = 'OPTION_END_REWORK';
export const OPTION_START_TEST_WORK = 'OPTION_START_TEST_WORK';
export const OPTION_END_TEST_WORK = 'OPTION_END_TEST_WORK';

// REPAIRMAN
export const OPTION_START_REPAIR = 'OPTION_START_REPAIR';
export const OPTION_END_REPAIR = 'OPTION_END_REPAIR';

// ITECHNIK
export const OPTION_INSTALL_TERMINAL = 'OPTION_INSTALL_TERMINAL';
export const OPTION_RESET_TERMINAL = 'OPTION_RESET_TERMINAL';